server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

producer-app:
  consumer-server-url: "localhost"
  consumer-server-port: 9003
  cors:
    enabled: true
    allowed-origins:
      - "*"
    allowed-origins-all: true
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"

logging:
  level:
    root: info